### ISSUE TITLE
Validate passwords beyond 15 characters

### ISSUE THREAD

**Issue by codindelhill** [JamalBelilet/regexed_validator#1]
The password '0123456789Abcdef#' will be treated as invalid even though it contains at least one of each type of character. This is because the regex only checks the first 15 characters for the pattern and the symbol '#' appears at the 16:th position. The same thing happens if only one upper case character appears in the 16:th position etc. Perhaps increase the limit beyond any reasonable password length? Or is it possible to use the same regex for an unspecified number of characters?

**Comment by JamalBelilet** [comment]
I am closing this issue since it have been resolved here: [,](https://github.com/JamalBelilet/regexed_validator/pull/2)

@codindelhill thank you for submitting the issue and the pull request.
