### ISSUE TITLE
Email validator not working correctly

### ISSUE THREAD

**Issue by MattheusOliveira** [JamalBelilet/regexed_validator#4]
Example: matheus@gmail.com (it working)
Now: matheus@gmail.com[] (it not working)
[] -> this means a space bar

**Comment by JamalBelilet** [comment]
This is an intended behavior, you'll need to `myText.trim()` your text before the validation, one basic rule of string validation and sanitisation is to produce the minimal valid group of options, allowing whitespaces will open unnecessary options, and that's something we don't wont to have.
