### ISSUE TITLE
Password length

### ISSUE THREAD

**Issue by ed-mota-teixeira** [JamalBelilet/regexed_validator#5]
Hi.
"Strong" passwords should have a minimum of 10 characters. I believe it's currently set for 8 ?

[Source](https://en.wikipedia.org/wiki/Password_strength)

**Comment by JamalBelilet** [comment]
Hello, @ed-mota-teixeira 
It is set to 8 to allow a wider range of possibilities!
For your specific case, it makes sense to check the length of your String(s) directly with Dart.

Best!
